import type { Meta, StoryObj } from '@storybook/vue3'
import TextField from './TextField.vue'

type Story = StoryObj<typeof Object>

const meta: Meta<typeof Object> = {
  title: 'Components/Atomic/TextField',
  component: TextField,
  tags: ['autodocs'],
  argTypes: {
    'active': { control: { type: 'boolean' }, description: 'アイテムのアクティブ状態を制御、ハイライトするために使用される' },
    'append-icon': { control: { type: 'text' }, description: 'アイテムの末尾にアイコンを追加' },
    'append-inner-icon': { control: { type: 'text' }, description: 'アイテムの末尾にアイコンを追加' },
    'autofocus': { control: { type: 'boolean' }, description: '自動フォーカス' },
    'base-color': { control: { type: 'text' }, description: 'ベースカラー' },
    'bg-color': { control: { type: 'text' }, description: '背景色' },
    'center-affix': { control: { type: 'boolean' }, description: 'アイコンを中央揃え' },
    'clearable': { control: { type: 'boolean' }, description: 'クリアボタンを表示' },
    'clear-icon': { control: { type: 'text' }, description: 'クリアアイコン' },
    'color': { control: { type: 'text' }, description: 'テキストカラー' },
    'counter': { control: { type: 'boolean' }, description: 'カウンターを表示' },
    'counter-value': { control: { type: 'number' }, description: 'カウンターの値' },
    'density': { control: { type: 'select' }, options: ['default', 'comfortable', 'compact'], description: '手動でダーティー状態のスタイリングを適用する' },
    'direction': { control: { type: 'select' }, options: ['horizontal', 'vertical'], description: '入力の方向を変更します。' },
    'dirty': { control: { type: 'boolean' }, description: 'ダーティ状態' },
    'disabled': { control: { type: 'boolean' }, description: '無効状態' },
    'error': { control: { type: 'boolean' }, description: 'エラー状態' },
    'error-messages': { control: { type: 'text' }, description: 'エラーメッセージ' },
    'flat': { control: { type: 'boolean' }, description: 'フラットスタイル' },
    'forcused': { control: { type: 'boolean' }, description: 'フォーカス状態' },
    'hide-details': { control: { type: 'select' }, options: ['auto', true, false], description: 'ヒントとバリデーションエラーを非表示にします。auto に設定すると、表示すべきメッセージ (ヒント、エラーメッセージ、カウンタ値など) がある場合にのみメッセージが表示されます。' },
    'hide-spin-buttons': { control: { type: 'boolean' }, description: 'タイプが数字に設定されている場合、入力上のスピンボタンを非表示にする。' },
    'hint': { control: { type: 'text' }, description: 'ヒント' },
    'id': { control: { type: 'text' }, description: 'ID' },
    'label': { control: { type: 'text' }, description: 'ラベル' },
    'loading': { control: { type: 'boolean' }, description: 'ローディング状態' },
    'max-errors': { control: { type: 'number' }, description: 'エラーメッセージの最大数' },
    'max-width': { control: { type: 'text' }, description: '最大幅' },
    'messages': { control: { type: 'text' }, description: 'メッセージ' },
    'min-width': { control: { type: 'text' }, description: '最小幅' },
    'model-value': { control: { type: 'text' }, description: 'モデル値' },
    'name': { control: { type: 'text' }, description: '名前' },
    'persistent-clear': { control: { type: 'boolean' }, description: '入力がダーティな場合は常にクリア可能なアイコンを表示します (デフォルトではホバー時にのみ表示されます)。' },
    'persistent-counter': { control: { type: 'boolean' }, description: 'カウンターを常に表示' },
    'persistent-hint': { control: { type: 'boolean' }, description: 'ヒントを常に表示' },
    'persistent-placeholder': { control: { type: 'boolean' }, description: 'プレースホルダーを常に表示' },
    'placeholder': { control: { type: 'text' }, description: 'プレースホルダー' },
    'prefix': { control: { type: 'text' }, description: 'プレフィックス' },
    'prepend-icon': { control: { type: 'text' }, description: 'アイテムの先頭にアイコンを追加(入力の外側)' },
    'prepend-inner-icon': { control: { type: 'text' }, description: 'アイテムの先頭にアイコンを追加(入力の内側)' },
    'readonly': { control: { type: 'boolean' }, description: '読み取り専用' },
    'reverse': { control: { type: 'boolean' }, description: '入力方向を反転します。' },
    'role': { control: { type: 'text' }, description: 'ロール' },
    'rounded': { control: { type: 'boolean' }, description: '境界の半径を追加します' },
    'rules': { control: { type: 'text' }, description: 'ルール' },
    'single-line': { control: { type: 'boolean' }, description: 'シングルライン' },
    'suffix': { control: { type: 'text' }, description: 'サフィックス' },
    'theme': { control: { type: 'text' }, description: 'このコンポーネントとそのすべての子のテーマを指定します。' },
    'tile': { control: { type: 'boolean' }, description: 'border-radiusを削除します' },
    'type': { control: { type: 'select' }, options: ['text', 'password', 'email', 'number', 'tel', 'url'], description: '入力タイプ' },
    'validate-on': { control: { type: 'select' }, options: ['blur', 'input', 'submit', 'blur lazy', 'input lazy', 'submit lazy', 'lazy blur', 'lazy input', 'lazy submit', 'lazy'], description: 'バリデーションをトリガーするイベント' },
    'validation-value': { control: { type: 'text' }, description: 'バリデーション値' },
    'variant': { control: { type: 'select' }, options: ['outlined', 'filled'] },
    'width': { control: { type: 'text' }, description: '幅' },
  },
  render: args => ({
    components: { TextField },
    setup() {
      return { args }
    },
    template: '<TextField v-bind="args" />',
  }),
}

export const Default: Story = {
  args: {
    'active': false,
    'append-icon': undefined,
    'append-inner-icon': undefined,
    'autofocus': false,
    'base-color': undefined,
    'bg-color': undefined,
    'center-affix': undefined,
    'clearable': false,
    'clear-icon': '$clear',
    'color': 'primary',
    'counter': false,
    'counter-value': undefined,
    'density': 'default',
    'direction': 'horizontal',
    'dirty': false,
    'disabled': null,
    'error': false,
    'error-messages': undefined,
    'flat': false,
    'forcused': false,
    'hide-details': false,
    'hide-spin-buttons': false,
    'hint': undefined,
    'id': undefined,
    'label': 'text field',
    'loading': false,
    'max-errors': 1,
    'max-width': undefined,
    'messages': undefined,
    'min-width': undefined,
    'model-value': undefined,
    'name': undefined,
    'persistent-clear': false,
    'persistent-counter': false,
    'persistent-hint': false,
    'persistent-placeholder': false,
    'placeholder': undefined,
    'prefix': undefined,
    'prepend-icon': undefined,
    'prepend-inner-icon': undefined,
    'readonly': null,
    'reverse': false,
    'role': undefined,
    'rounded': undefined,
    'rules': undefined,
    'single-line': false,
    'suffix': undefined,
    'theme': undefined,
    'tile': false,
    'type': 'text',
    'validate-on': undefined,
    'validation-value': undefined,
    'variant': 'outlined',
    'width': undefined,
  },
}

export default meta
